name: GPU Enabled Functional Test on PRs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - ci-*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  OPTIMUM_NVIDIA_IS_CI: ON
  RUN_CPU_ONLY: OFF
  RUN_NIGHTLY: OFF
  RUN_SLOW: ON
  HF_HUB_ENABLE_HF_TRANSFER: ON

jobs:
  run_gpu_tests:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: GPU-enabled Optimum-Nvidia Integration Test Suite
            image: huggingface/optimum-nvidia:ci
#        cuda_arch: [sm_86, sm_89]
        cuda_arch: [sm_89]

    name: ${{ matrix.config.name }}
    runs-on: [ci, nvidia-gpu, multi-gpu, "${{ matrix.cuda_arch }}"]

    container:
      image: ${{ matrix.config.image }}
      options: --gpus all --ipc host -v /mnt/hf_cache:/mnt/cache/
      env:
        HF_TOKEN: ${{ secrets.OPTIMUM_NVIDIA_HUB_READ_TOKEN }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout optimum-nvidia
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Uninstall optimum-nvidia before doing anything
        run: |
          python -m pip uninstall -y optimum-nvidia

      - name: Install dependencies
        run: |
          python -m pip install --upgrade -e .[quality,tests]

      - name: Run optimum-nvidia integration test-suite
        run: |
          python -m pytest -s -v -n 1 -p no:warnings tests/integration/